/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { login } from '../fn/auth/login';
import { Login$Params } from '../fn/auth/login';
import { logout } from '../fn/auth/logout';
import { Logout$Params } from '../fn/auth/logout';
import { me } from '../fn/auth/me';
import { Me$Params } from '../fn/auth/me';
import { requestPasswordReset } from '../fn/auth/request-password-reset';
import { RequestPasswordReset$Params } from '../fn/auth/request-password-reset';
import { resendVerification } from '../fn/auth/resend-verification';
import { ResendVerification$Params } from '../fn/auth/resend-verification';
import { resetPassword } from '../fn/auth/reset-password';
import { ResetPassword$Params } from '../fn/auth/reset-password';
import { signup } from '../fn/auth/signup';
import { Signup$Params } from '../fn/auth/signup';
import { UserPublic } from '../models/user-public';
import { verifyEmail } from '../fn/auth/verify-email';
import { VerifyEmail$Params } from '../fn/auth/verify-email';

@Injectable({ providedIn: 'root' })
export class AuthService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `signup()` */
  static readonly SignupPath = '/auth/signup';

  /**
   * Create an account and send a verification email (§3).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `signup()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  signup$Response(params: Signup$Params, context?: HttpContext): Promise<StrictHttpResponse<UserPublic>> {
    const obs = signup(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Create an account and send a verification email (§3).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `signup$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  signup(params: Signup$Params, context?: HttpContext): Promise<UserPublic> {
    const resp = this.signup$Response(params, context);
    return resp.then((r: StrictHttpResponse<UserPublic>): UserPublic => r.body);
  }

  /** Path part for operation `verifyEmail()` */
  static readonly VerifyEmailPath = '/auth/verify';

  /**
   * Consume a verification token (§3, ADR-9).
   *
   * Idempotent for verified accounts — a second call with the same token returns already_verified (double-click / StrictMode safe).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `verifyEmail()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  verifyEmail$Response(params: VerifyEmail$Params, context?: HttpContext): Promise<StrictHttpResponse<{
'status': 'verified' | 'already_verified';
}>> {
    const obs = verifyEmail(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Consume a verification token (§3, ADR-9).
   *
   * Idempotent for verified accounts — a second call with the same token returns already_verified (double-click / StrictMode safe).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `verifyEmail$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  verifyEmail(params: VerifyEmail$Params, context?: HttpContext): Promise<{
'status': 'verified' | 'already_verified';
}> {
    const resp = this.verifyEmail$Response(params, context);
    return resp.then((r: StrictHttpResponse<{
'status': 'verified' | 'already_verified';
}>): {
'status': 'verified' | 'already_verified';
} => r.body);
  }

  /** Path part for operation `resendVerification()` */
  static readonly ResendVerificationPath = '/auth/resend-verification';

  /**
   * Reissue a verification email (§3, ADR-6).
   *
   * Always 200 with a generic message. Reissues only for existing, unverified accounts; a new token invalidates earlier ones by overwrite (ADR-9).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `resendVerification()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  resendVerification$Response(params: ResendVerification$Params, context?: HttpContext): Promise<StrictHttpResponse<{
'message': string;
}>> {
    const obs = resendVerification(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Reissue a verification email (§3, ADR-6).
   *
   * Always 200 with a generic message. Reissues only for existing, unverified accounts; a new token invalidates earlier ones by overwrite (ADR-9).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `resendVerification$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  resendVerification(params: ResendVerification$Params, context?: HttpContext): Promise<{
'message': string;
}> {
    const resp = this.resendVerification$Response(params, context);
    return resp.then((r: StrictHttpResponse<{
'message': string;
}>): {
'message': string;
} => r.body);
  }

  /** Path part for operation `requestPasswordReset()` */
  static readonly RequestPasswordResetPath = '/auth/request-password-reset';

  /**
   * Request a password reset email (S8.4, ADR-17).
   *
   * Always 200 with a generic message (no account enumeration). Mails a token only to existing, VERIFIED accounts — unverified accounts use resend-verification instead, keeping the two token flows orthogonal. A new request invalidates any earlier unused reset token by overwrite.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `requestPasswordReset()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  requestPasswordReset$Response(params: RequestPasswordReset$Params, context?: HttpContext): Promise<StrictHttpResponse<{
'message': string;
}>> {
    const obs = requestPasswordReset(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Request a password reset email (S8.4, ADR-17).
   *
   * Always 200 with a generic message (no account enumeration). Mails a token only to existing, VERIFIED accounts — unverified accounts use resend-verification instead, keeping the two token flows orthogonal. A new request invalidates any earlier unused reset token by overwrite.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `requestPasswordReset$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  requestPasswordReset(params: RequestPasswordReset$Params, context?: HttpContext): Promise<{
'message': string;
}> {
    const resp = this.requestPasswordReset$Response(params, context);
    return resp.then((r: StrictHttpResponse<{
'message': string;
}>): {
'message': string;
} => r.body);
  }

  /** Path part for operation `resetPassword()` */
  static readonly ResetPasswordPath = '/auth/reset-password';

  /**
   * Consume a reset token and set a new password (S8.4, ADR-17).
   *
   * Single-use — the token is cleared on success. Expires after 1 hour (shorter than the 24h verification TTL; a reset token grants account takeover). On success, ALL of the account's existing sessions are revoked, not just the one making this request.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `resetPassword()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  resetPassword$Response(params: ResetPassword$Params, context?: HttpContext): Promise<StrictHttpResponse<{
'message': string;
}>> {
    const obs = resetPassword(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Consume a reset token and set a new password (S8.4, ADR-17).
   *
   * Single-use — the token is cleared on success. Expires after 1 hour (shorter than the 24h verification TTL; a reset token grants account takeover). On success, ALL of the account's existing sessions are revoked, not just the one making this request.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `resetPassword$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  resetPassword(params: ResetPassword$Params, context?: HttpContext): Promise<{
'message': string;
}> {
    const resp = this.resetPassword$Response(params, context);
    return resp.then((r: StrictHttpResponse<{
'message': string;
}>): {
'message': string;
} => r.body);
  }

  /** Path part for operation `login()` */
  static readonly LoginPath = '/auth/login';

  /**
   * Log in (§3, ADR-3, ADR-8).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `login()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  login$Response(params: Login$Params, context?: HttpContext): Promise<StrictHttpResponse<UserPublic>> {
    const obs = login(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Log in (§3, ADR-3, ADR-8).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `login$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  login(params: Login$Params, context?: HttpContext): Promise<UserPublic> {
    const resp = this.login$Response(params, context);
    return resp.then((r: StrictHttpResponse<UserPublic>): UserPublic => r.body);
  }

  /** Path part for operation `logout()` */
  static readonly LogoutPath = '/auth/logout';

  /**
   * Destroy the session server-side and clear the cookie (ADR-8).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `logout()` instead.
   *
   * This method doesn't expect any request body.
   */
  logout$Response(params?: Logout$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = logout(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Destroy the session server-side and clear the cookie (ADR-8).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `logout$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  logout(params?: Logout$Params, context?: HttpContext): Promise<void> {
    const resp = this.logout$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `me()` */
  static readonly MePath = '/auth/me';

  /**
   * Current user for the header menu.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `me()` instead.
   *
   * This method doesn't expect any request body.
   */
  me$Response(params?: Me$Params, context?: HttpContext): Promise<StrictHttpResponse<UserPublic>> {
    const obs = me(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Current user for the header menu.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `me$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  me(params?: Me$Params, context?: HttpContext): Promise<UserPublic> {
    const resp = this.me$Response(params, context);
    return resp.then((r: StrictHttpResponse<UserPublic>): UserPublic => r.body);
  }

}
