/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Comment } from '../models/comment';
import { createComment } from '../fn/comments/create-comment';
import { CreateComment$Params } from '../fn/comments/create-comment';
import { deleteComment } from '../fn/comments/delete-comment';
import { DeleteComment$Params } from '../fn/comments/delete-comment';
import { listComments } from '../fn/comments/list-comments';
import { ListComments$Params } from '../fn/comments/list-comments';
import { updateComment } from '../fn/comments/update-comment';
import { UpdateComment$Params } from '../fn/comments/update-comment';

@Injectable({ providedIn: 'root' })
export class CommentsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listComments()` */
  static readonly ListCommentsPath = '/tickets/{id}/comments';

  /**
   * Comments of a ticket, oldest first (§7).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listComments()` instead.
   *
   * This method doesn't expect any request body.
   */
  listComments$Response(params: ListComments$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Comment>>> {
    const obs = listComments(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Comments of a ticket, oldest first (§7).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listComments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listComments(params: ListComments$Params, context?: HttpContext): Promise<Array<Comment>> {
    const resp = this.listComments$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Comment>>): Array<Comment> => r.body);
  }

  /** Path part for operation `createComment()` */
  static readonly CreateCommentPath = '/tickets/{id}/comments';

  /**
   * Add a comment (§7).
   *
   * Author from session. MUST NOT touch the ticket's modifiedAt (§7). Editable/deletable by its author only — see PATCH/DELETE below (S8.1, §14).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createComment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createComment$Response(params: CreateComment$Params, context?: HttpContext): Promise<StrictHttpResponse<Comment>> {
    const obs = createComment(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Add a comment (§7).
   *
   * Author from session. MUST NOT touch the ticket's modifiedAt (§7). Editable/deletable by its author only — see PATCH/DELETE below (S8.1, §14).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createComment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createComment(params: CreateComment$Params, context?: HttpContext): Promise<Comment> {
    const resp = this.createComment$Response(params, context);
    return resp.then((r: StrictHttpResponse<Comment>): Comment => r.body);
  }

  /** Path part for operation `deleteComment()` */
  static readonly DeleteCommentPath = '/tickets/{id}/comments/{commentId}';

  /**
   * Delete own comment (S8.1, §7/§14).
   *
   * Author-only, hard delete. MUST NOT touch the ticket's modifiedAt (§7).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteComment()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteComment$Response(params: DeleteComment$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = deleteComment(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Delete own comment (S8.1, §7/§14).
   *
   * Author-only, hard delete. MUST NOT touch the ticket's modifiedAt (§7).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteComment$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteComment(params: DeleteComment$Params, context?: HttpContext): Promise<void> {
    const resp = this.deleteComment$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `updateComment()` */
  static readonly UpdateCommentPath = '/tickets/{id}/comments/{commentId}';

  /**
   * Edit own comment (S8.1, §7/§14).
   *
   * Author-only. Sets editedAt server-side. MUST NOT touch the ticket's modifiedAt (§7).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateComment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateComment$Response(params: UpdateComment$Params, context?: HttpContext): Promise<StrictHttpResponse<Comment>> {
    const obs = updateComment(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Edit own comment (S8.1, §7/§14).
   *
   * Author-only. Sets editedAt server-side. MUST NOT touch the ticket's modifiedAt (§7).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateComment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateComment(params: UpdateComment$Params, context?: HttpContext): Promise<Comment> {
    const resp = this.updateComment$Response(params, context);
    return resp.then((r: StrictHttpResponse<Comment>): Comment => r.body);
  }

}
