/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createEpic } from '../fn/epics/create-epic';
import { CreateEpic$Params } from '../fn/epics/create-epic';
import { deleteEpic } from '../fn/epics/delete-epic';
import { DeleteEpic$Params } from '../fn/epics/delete-epic';
import { Epic } from '../models/epic';
import { listEpics } from '../fn/epics/list-epics';
import { ListEpics$Params } from '../fn/epics/list-epics';
import { updateEpic } from '../fn/epics/update-epic';
import { UpdateEpic$Params } from '../fn/epics/update-epic';

@Injectable({ providedIn: 'root' })
export class EpicsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listEpics()` */
  static readonly ListEpicsPath = '/epics';

  /**
   * List epics for one team (§5, wireframe 5).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listEpics()` instead.
   *
   * This method doesn't expect any request body.
   */
  listEpics$Response(params: ListEpics$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Epic>>> {
    const obs = listEpics(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * List epics for one team (§5, wireframe 5).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listEpics$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listEpics(params: ListEpics$Params, context?: HttpContext): Promise<Array<Epic>> {
    const resp = this.listEpics$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Epic>>): Array<Epic> => r.body);
  }

  /** Path part for operation `createEpic()` */
  static readonly CreateEpicPath = '/epics';

  /**
   * Create an epic bound to a team (§5 — team immutable afterwards).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createEpic()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createEpic$Response(params: CreateEpic$Params, context?: HttpContext): Promise<StrictHttpResponse<Epic>> {
    const obs = createEpic(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Create an epic bound to a team (§5 — team immutable afterwards).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createEpic$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createEpic(params: CreateEpic$Params, context?: HttpContext): Promise<Epic> {
    const resp = this.createEpic$Response(params, context);
    return resp.then((r: StrictHttpResponse<Epic>): Epic => r.body);
  }

  /** Path part for operation `deleteEpic()` */
  static readonly DeleteEpicPath = '/epics/{id}';

  /**
   * Delete an epic (§5, §9).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteEpic()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteEpic$Response(params: DeleteEpic$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = deleteEpic(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Delete an epic (§5, §9).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteEpic$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteEpic(params: DeleteEpic$Params, context?: HttpContext): Promise<void> {
    const resp = this.deleteEpic$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `updateEpic()` */
  static readonly UpdateEpicPath = '/epics/{id}';

  /**
   * Edit epic title/description (§5).
   *
   * No teamId field exists — the team is immutable (§5). No-op saves do not advance modifiedAt.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateEpic()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateEpic$Response(params: UpdateEpic$Params, context?: HttpContext): Promise<StrictHttpResponse<Epic>> {
    const obs = updateEpic(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Edit epic title/description (§5).
   *
   * No teamId field exists — the team is immutable (§5). No-op saves do not advance modifiedAt.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateEpic$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateEpic(params: UpdateEpic$Params, context?: HttpContext): Promise<Epic> {
    const resp = this.updateEpic$Response(params, context);
    return resp.then((r: StrictHttpResponse<Epic>): Epic => r.body);
  }

}
