/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { health } from '../fn/system/health';
import { Health$Params } from '../fn/system/health';

@Injectable({ providedIn: 'root' })
export class SystemService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `health()` */
  static readonly HealthPath = '/health';

  /**
   * Health/readiness (public, §3).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `health()` instead.
   *
   * This method doesn't expect any request body.
   */
  health$Response(params?: Health$Params, context?: HttpContext): Promise<StrictHttpResponse<{
'status': 'ok';
}>> {
    const obs = health(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Health/readiness (public, §3).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `health$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  health(params?: Health$Params, context?: HttpContext): Promise<{
'status': 'ok';
}> {
    const resp = this.health$Response(params, context);
    return resp.then((r: StrictHttpResponse<{
'status': 'ok';
}>): {
'status': 'ok';
} => r.body);
  }

}
