/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createTeam } from '../fn/teams/create-team';
import { CreateTeam$Params } from '../fn/teams/create-team';
import { deleteTeam } from '../fn/teams/delete-team';
import { DeleteTeam$Params } from '../fn/teams/delete-team';
import { listTeams } from '../fn/teams/list-teams';
import { ListTeams$Params } from '../fn/teams/list-teams';
import { Team } from '../models/team';
import { updateTeam } from '../fn/teams/update-team';
import { UpdateTeam$Params } from '../fn/teams/update-team';

@Injectable({ providedIn: 'root' })
export class TeamsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listTeams()` */
  static readonly ListTeamsPath = '/teams';

  /**
   * List all teams with counts (wireframe 4).
   *
   * Ordered by name, case-insensitive ascending.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listTeams()` instead.
   *
   * This method doesn't expect any request body.
   */
  listTeams$Response(params?: ListTeams$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Team>>> {
    const obs = listTeams(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * List all teams with counts (wireframe 4).
   *
   * Ordered by name, case-insensitive ascending.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listTeams$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listTeams(params?: ListTeams$Params, context?: HttpContext): Promise<Array<Team>> {
    const resp = this.listTeams$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Team>>): Array<Team> => r.body);
  }

  /** Path part for operation `createTeam()` */
  static readonly CreateTeamPath = '/teams';

  /**
   * Create a team (§4).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createTeam()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createTeam$Response(params: CreateTeam$Params, context?: HttpContext): Promise<StrictHttpResponse<Team>> {
    const obs = createTeam(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Create a team (§4).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createTeam$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createTeam(params: CreateTeam$Params, context?: HttpContext): Promise<Team> {
    const resp = this.createTeam$Response(params, context);
    return resp.then((r: StrictHttpResponse<Team>): Team => r.body);
  }

  /** Path part for operation `deleteTeam()` */
  static readonly DeleteTeamPath = '/teams/{id}';

  /**
   * Delete a team (§4, §9).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteTeam()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTeam$Response(params: DeleteTeam$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = deleteTeam(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Delete a team (§4, §9).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteTeam$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTeam(params: DeleteTeam$Params, context?: HttpContext): Promise<void> {
    const resp = this.deleteTeam$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `updateTeam()` */
  static readonly UpdateTeamPath = '/teams/{id}';

  /**
   * Rename a team (§4).
   *
   * Uniqueness check excludes the team itself — case-only renames succeed. A no-op rename does not advance modifiedAt.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateTeam()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTeam$Response(params: UpdateTeam$Params, context?: HttpContext): Promise<StrictHttpResponse<Team>> {
    const obs = updateTeam(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Rename a team (§4).
   *
   * Uniqueness check excludes the team itself — case-only renames succeed. A no-op rename does not advance modifiedAt.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateTeam$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTeam(params: UpdateTeam$Params, context?: HttpContext): Promise<Team> {
    const resp = this.updateTeam$Response(params, context);
    return resp.then((r: StrictHttpResponse<Team>): Team => r.body);
  }

}
