/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createTicket } from '../fn/tickets/create-ticket';
import { CreateTicket$Params } from '../fn/tickets/create-ticket';
import { deleteTicket } from '../fn/tickets/delete-ticket';
import { DeleteTicket$Params } from '../fn/tickets/delete-ticket';
import { getTicket } from '../fn/tickets/get-ticket';
import { GetTicket$Params } from '../fn/tickets/get-ticket';
import { listTickets } from '../fn/tickets/list-tickets';
import { ListTickets$Params } from '../fn/tickets/list-tickets';
import { Ticket } from '../models/ticket';
import { updateTicket } from '../fn/tickets/update-ticket';
import { UpdateTicket$Params } from '../fn/tickets/update-ticket';

@Injectable({ providedIn: 'root' })
export class TicketsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listTickets()` */
  static readonly ListTicketsPath = '/tickets';

  /**
   * List all tickets of one team (ADR-7 — filtering is client-side).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listTickets()` instead.
   *
   * This method doesn't expect any request body.
   */
  listTickets$Response(params: ListTickets$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Ticket>>> {
    const obs = listTickets(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * List all tickets of one team (ADR-7 — filtering is client-side).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listTickets$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listTickets(params: ListTickets$Params, context?: HttpContext): Promise<Array<Ticket>> {
    const resp = this.listTickets$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Ticket>>): Array<Ticket> => r.body);
  }

  /** Path part for operation `createTicket()` */
  static readonly CreateTicketPath = '/tickets';

  /**
   * Create a ticket (§6).
   *
   * createdBy is taken from the session. state defaults to `new` but any of the five values is accepted (§8 allows any transition). modifiedAt = createdAt.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createTicket()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createTicket$Response(params: CreateTicket$Params, context?: HttpContext): Promise<StrictHttpResponse<Ticket>> {
    const obs = createTicket(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Create a ticket (§6).
   *
   * createdBy is taken from the session. state defaults to `new` but any of the five values is accepted (§8 allows any transition). modifiedAt = createdAt.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createTicket$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createTicket(params: CreateTicket$Params, context?: HttpContext): Promise<Ticket> {
    const resp = this.createTicket$Response(params, context);
    return resp.then((r: StrictHttpResponse<Ticket>): Ticket => r.body);
  }

  /** Path part for operation `getTicket()` */
  static readonly GetTicketPath = '/tickets/{id}';

  /**
   * Full ticket for the detail view (§6, wireframe 3).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTicket()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTicket$Response(params: GetTicket$Params, context?: HttpContext): Promise<StrictHttpResponse<Ticket>> {
    const obs = getTicket(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Full ticket for the detail view (§6, wireframe 3).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTicket$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTicket(params: GetTicket$Params, context?: HttpContext): Promise<Ticket> {
    const resp = this.getTicket$Response(params, context);
    return resp.then((r: StrictHttpResponse<Ticket>): Ticket => r.body);
  }

  /** Path part for operation `deleteTicket()` */
  static readonly DeleteTicketPath = '/tickets/{id}';

  /**
   * Delete a ticket and cascade its comments (§6).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteTicket()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTicket$Response(params: DeleteTicket$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = deleteTicket(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Delete a ticket and cascade its comments (§6).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteTicket$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTicket(params: DeleteTicket$Params, context?: HttpContext): Promise<void> {
    const resp = this.deleteTicket$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `updateTicket()` */
  static readonly UpdateTicketPath = '/tickets/{id}';

  /**
   * Partial update — form saves and board drags share this (ADR-5).
   *
   * Accepts any subset of editable fields; a drag sends {"state": "..."} only. The server validates the MERGED result (incoming ∪ stored): a merged epic that does not belong to the merged team → 400 EPIC_TEAM_MISMATCH (§6). No-op saves (all merged values equal stored) must not advance modifiedAt (§6); real changes set it server-side. Last write wins (§9).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateTicket()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTicket$Response(params: UpdateTicket$Params, context?: HttpContext): Promise<StrictHttpResponse<Ticket>> {
    const obs = updateTicket(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Partial update — form saves and board drags share this (ADR-5).
   *
   * Accepts any subset of editable fields; a drag sends {"state": "..."} only. The server validates the MERGED result (incoming ∪ stored): a merged epic that does not belong to the merged team → 400 EPIC_TEAM_MISMATCH (§6). No-op saves (all merged values equal stored) must not advance modifiedAt (§6); real changes set it server-side. Last write wins (§9).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateTicket$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTicket(params: UpdateTicket$Params, context?: HttpContext): Promise<Ticket> {
    const resp = this.updateTicket$Response(params, context);
    return resp.then((r: StrictHttpResponse<Ticket>): Ticket => r.body);
  }

}
