/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ResendVerification$Params {
      body: {
'email': string;
}
}

export function resendVerification(http: HttpClient, rootUrl: string, params: ResendVerification$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'message': string;
}>> {
  const rb = new RequestBuilder(rootUrl, resendVerification.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'message': string;
      }>;
    })
  );
}

resendVerification.PATH = '/auth/resend-verification';
