/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Credentials } from '../../models/credentials';
import { UserPublic } from '../../models/user-public';

export interface Signup$Params {
      body: Credentials
}

export function signup(http: HttpClient, rootUrl: string, params: Signup$Params, context?: HttpContext): Observable<StrictHttpResponse<UserPublic>> {
  const rb = new RequestBuilder(rootUrl, signup.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserPublic>;
    })
  );
}

signup.PATH = '/auth/signup';
