/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface VerifyEmail$Params {
      body: {
'token': string;
}
}

export function verifyEmail(http: HttpClient, rootUrl: string, params: VerifyEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'status': 'verified' | 'already_verified';
}>> {
  const rb = new RequestBuilder(rootUrl, verifyEmail.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'status': 'verified' | 'already_verified';
      }>;
    })
  );
}

verifyEmail.PATH = '/auth/verify';
