/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Credentials {

  /**
   * Trimmed + lowercased server-side before any comparison (ADR-12)
   */
  email: string;

  /**
   * Never trimmed or normalized (spec-analysis); min 8 per §3
   */
  password: string;
}
