/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EpicCreate {
  description?: string | null;

  /**
   * Immutable after creation (§5)
   */
  teamId: number;
  title: string;
}
