/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * teamId deliberately absent — epics cannot move teams (§5); unknown keys are rejected with 400 (strict schema)
 */
export interface EpicUpdate {
  description?: string | null;
  title?: string;
}
