/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Error {
  error: {

/**
 * Machine-readable; the full set used — UNAUTHENTICATED, INVALID_CREDENTIALS, EMAIL_NOT_VERIFIED, EMAIL_TAKEN, TOKEN_EXPIRED, TOKEN_INVALID, VALIDATION, NOT_FOUND, FORBIDDEN, DUPLICATE_TEAM_NAME, TEAM_NOT_EMPTY, EPIC_REFERENCED, EPIC_TEAM_MISMATCH, INTERNAL (unexpected server error — 500)
 */
'code': string;
'message': string;

/**
 * Present when the error is attributable to one request field
 */
'field'?: string;
};
}
