/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Team {
  createdAt: string;
  epicCount: number;
  id: number;
  modifiedAt: string;
  name: string;

  /**
   * Drives the disabled-delete affordance (wireframe 4)
   */
  ticketCount: number;
}
