/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * §6 canonical values in workflow order; UI renders human labels
 */
export type TicketState = 'new' | 'ready_for_implementation' | 'in_progress' | 'ready_for_acceptance' | 'done';

