/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TicketState } from '../models/ticket-state';
import { TicketType } from '../models/ticket-type';

/**
 * Any subset of the KNOWN fields (ADR-5); a board drag sends only {state}; unknown keys are rejected with 400 (strict schema). Merged-state validation applies (§6).
 */
export interface TicketUpdate {
  body?: string;
  epicId?: number | null;
  state?: TicketState;
  teamId?: number;
  title?: string;
  type?: TicketType;
}
