/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TicketState } from './ticket-state';

/**
 * Each possible value of `TicketState`
 */
export const TICKET_STATE: TicketState[] = [
  'new',
  'ready_for_implementation',
  'in_progress',
  'ready_for_acceptance',
  'done'
];