/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TicketState } from '../models/ticket-state';
import { TicketType } from '../models/ticket-type';
import { UserPublic } from '../models/user-public';
export interface Ticket {
  body: string;
  createdAt: string;
  createdBy: UserPublic;

  /**
   * Clients resolve the epic title from the team's epic list (ADR-7)
   */
  epicId: number | null;

  /**
   * Displayed as "#42" (ADR-4)
   */
  id: number;

  /**
   * Equals createdAt until the first real change (§6); board sort key (§8)
   */
  modifiedAt: string;
  state: TicketState;
  teamId: number;
  title: string;
  type: TicketType;
}
