/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Comment } from '../../models/comment';

export interface ListComments$Params {
  id: number;
}

export function listComments(http: HttpClient, rootUrl: string, params: ListComments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Comment>>> {
  const rb = new RequestBuilder(rootUrl, listComments.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Comment>>;
    })
  );
}

listComments.PATH = '/tickets/{id}/comments';
