/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Epic } from '../../models/epic';
import { EpicCreate } from '../../models/epic-create';

export interface CreateEpic$Params {
      body: EpicCreate
}

export function createEpic(http: HttpClient, rootUrl: string, params: CreateEpic$Params, context?: HttpContext): Observable<StrictHttpResponse<Epic>> {
  const rb = new RequestBuilder(rootUrl, createEpic.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Epic>;
    })
  );
}

createEpic.PATH = '/epics';
