/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Epic } from '../../models/epic';

export interface ListEpics$Params {

/**
 * Missing/invalid → 400; a teamId that matches no team → 404
 */
  teamId: number;
}

export function listEpics(http: HttpClient, rootUrl: string, params: ListEpics$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Epic>>> {
  const rb = new RequestBuilder(rootUrl, listEpics.PATH, 'get');
  if (params) {
    rb.query('teamId', params.teamId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Epic>>;
    })
  );
}

listEpics.PATH = '/epics';
