/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Epic } from '../../models/epic';
import { EpicUpdate } from '../../models/epic-update';

export interface UpdateEpic$Params {
  id: number;
      body: EpicUpdate
}

export function updateEpic(http: HttpClient, rootUrl: string, params: UpdateEpic$Params, context?: HttpContext): Observable<StrictHttpResponse<Epic>> {
  const rb = new RequestBuilder(rootUrl, updateEpic.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Epic>;
    })
  );
}

updateEpic.PATH = '/epics/{id}';
